export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_ID = "GET_PRODUCTS_ID";
export const GET_PRODUCTS_NAME = "GET_PRODUCTS_NAME";
export const GET_PRODUCTS_CATEGORY = "GET_PRODUCTS_CATEGORY";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const CREATE_USER = "CREATE_USER";
export const CREATE_ADMIN = "CREATE_ADMIN";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_PASSWORD_USER = "UPDATE_PASSWORD_USER";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const LOGIN = "LOGIN";
